apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: falco
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 7.0.2
    helm:
      values:
        namespaceOverride: "falco"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOpions:
      - CreateNamespace=true
